import {
  AccountCircle as Person,
  AddShoppingCart,
  ArrowBack,
  ArrowForward,
  Business,
  Cancel,
  Chat as Support,
  Check,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  Close,
  CreditCard,
  Email,
  Error as ErrorIcon,
  ExpandMore,
  Favorite,
  FavoriteBorder,
  FilterList,
  FilterListOff,
  Groups,
  Home,
  LocalShipping,
  Lock,
  LocationOn,
  Map,
  Menu,
  MoreVert,
  Nature,
  Person as PersonIcon,
  Refresh,
  Save,
  Search,
  Send,
  ShoppingBasket,
  ShoppingCart,
  Star,
  Store,
  SupportAgent,
  ThumbUp,
  TrendingUp,
  Undo,
  VerifiedUser,
  Visibility,
  VisibilityOff,
  KeyboardArrowLeft,
  KeyboardArrowRight,
  PhoneAndroid as Phone,
  YouTube as YouTubeIcon,
  Twitter as TwitterIcon,
  Instagram as InstagramIcon,
  Facebook as FacebookIcon,
  Help,
  Verified,
  AttachMoney,
  Inventory2,
  Description,
  People,
  Receipt,
  CalendarToday,
  Payment,
  Inventory,
  LocalOffer,
  Shield,
  Favorite as FavoriteIcon,
} from "@mui/icons-material";

export const Icons = {
  // Navigation
  Menu,
  Close,
  ChevronLeft,
  ChevronRight,
  ArrowBack,
  ArrowForward,
  MoreVert,
  ExpandMore,
  Search,
  Home,
  Person,
  PersonIcon,
  AccountCircle: Person,
  
  // Commerce
  ShoppingCart,
  AddShoppingCart,
  ShoppingBasket,
  Store,
  CreditCard,
  AttachMoney,
  Inventory,
  Inventory2,
  LocalOffer,
  Receipt,
  Payment,
  
  // Actions
  Save,
  Refresh,
  Undo,
  Delete: Cancel,
  Cancel,
  Check,
  CheckCircle,
  Error: ErrorIcon,
  Star,
  Favorite,
  FavoriteBorder,
  FavoriteIcon,
  ThumbUp,
  Verified: VerifiedUser,
  VerifiedUser,
  Shield,
  Description,
  
  // Communication
  Email,
  Send,
  Phone,
  Support: SupportAgent,
  SupportAgent,
  Chat: SupportAgent,
  Help,
  Business,
  Groups,
  People,
  
  // UI Elements
  Visibility,
  VisibilityOff,
  KeyboardArrowLeft,
  KeyboardArrowRight,
  LocationOn,
  LocalShipping,
  Map,
  CalendarToday,
  Lock,
  Trending: TrendingUp,
  TrendingUp,
  FilterList,
  FilterListOff,
  Nature,
  VerifiedUser2: VerifiedUser,
  
  // Social
  Facebook: FacebookIcon,
  Twitter: TwitterIcon,
  Instagram: InstagramIcon,
  YouTube: YouTubeIcon,
  
  // Form
  EmailIcon: Email,
  LockIcon: Lock,
  PersonIcon2: Person,
  
  // Specific aliases for common use cases
  CartIcon: ShoppingCart,
  ShippingIcon: LocalShipping,
  VerifiedIcon: VerifiedUser,
  SupportIcon: SupportAgent,
  ErrorIcon,
  ErrorIcon2: ErrorIcon,
  RefreshIcon: Refresh,
  CancelIcon: Cancel,
  CheckIcon: Check,
  SaveIcon: Save,
  VisibilityIcon: Visibility,
  VisibilityOffIcon: VisibilityOff,
  StarIcon: Star,
  AddIcon: AddShoppingCart,
  EditIcon: Save,
  DeleteIcon: Cancel,
  SearchIcon: Search,
  FilterIcon: FilterList,
  HeartIcon: Favorite,
  HeartBorderIcon: FavoriteBorder,
  PersonIcon3: Person,
  PhoneIcon: Phone,
  LocationIcon: LocationOn,
  CalendarIcon: CalendarToday,
  CreditCardIcon: CreditCard,
  UndoIcon: Undo,
  SendIcon: Send,
  MapIcon: Map,
  SupportAgentIcon: SupportAgent,
  VerifiedIcon2: VerifiedUser,
  TrendingIcon: TrendingUp,
  MoreIcon: MoreVert,
  ExpandIcon: ExpandMore,
  FavoriteIcon2: Favorite,
  FavoriteBorderIcon2: FavoriteBorder,
  MenuIcon: Menu,
  CloseIcon: Close,
  ArrowBackIcon: ArrowBack,
  ArrowForwardIcon: ArrowForward,
  ChevronLeftIcon: ChevronLeft,
  ChevronRightIcon: ChevronRight,
  KeyboardArrowLeftIcon: KeyboardArrowLeft,
  KeyboardArrowRightIcon: KeyboardArrowRight,
  TrendingUpIcon: TrendingUp,
  NatureIcon: Nature,
  GroupsIcon: Groups,
  BusinessIcon: Business,
  ThumbUpIcon: ThumbUp,
  FacebookIcon2: FacebookIcon,
  TwitterIcon2: TwitterIcon,
  InstagramIcon2: InstagramIcon,
  YouTubeIcon2: YouTubeIcon,
  SupportAgentIcon2: SupportAgent,
  VerifiedIcon3: VerifiedUser,
  LockIcon2: Lock,
  EmailIcon2: Email,
};

export default Icons;