"use client";

import React from "react";
import {
  Menu as MenuIcon,
  ShoppingCart as ShoppingCartIcon,
  Favorite as FavoriteIcon,
  Search as SearchIcon,
  Person as PersonIcon,
  Close as CloseIcon,
  ExpandMore as ExpandMoreIcon,
  ChevronLeft as ChevronLeftIcon,
  KeyboardArrowLeft as KeyboardArrowLeftIcon,
  KeyboardArrowRight as KeyboardArrowRightIcon,
  LocalShipping as LocalShippingIcon,
  VerifiedUser as VerifiedUserIcon,
  SupportAgent as SupportAgentIcon,
  AddShoppingCart as AddShoppingCartIcon,
  ArrowBack as ArrowBackIcon,
  CreditCard as CreditCardIcon,
  Check as CheckIcon,
  CheckCircle as CheckCircleIcon,
  LocationOn as LocationOnIcon,
  Email as EmailIcon,
  Lock as LockIcon,
  Visibility as VisibilityIcon,
  VisibilityOff as VisibilityOffIcon,
  Star as StarIcon,
  Delete as DeleteIcon,
  MoreVert as MoreVertIcon,
  Refresh as RefreshIcon,
  Home as HomeIcon,
  TrendingUp as TrendingUpIcon,
  FilterList as FilterListIcon,
  Undo as UndoIcon,
  Send as SendIcon,
  ThumbUp as ThumbUpIcon,
  Nature as NatureIcon,
  Groups as GroupsIcon,
  Business as BusinessIcon,
  Phone as PhoneIcon,
  Map as MapIcon,
  CalendarToday as CalendarTodayIcon,
  Payment as PaymentIcon,
  AttachMoney as AttachMoneyIcon,
  Inventory as InventoryIcon,
  LocalOffer as LocalOfferIcon,
  Description as DescriptionIcon,
  People as PeopleIcon,
  Receipt as ReceiptIcon,
  Shield as ShieldIcon,
  CameraAlt as CameraAltIcon,
  YouTube as YouTubeIcon,
  Facebook as FacebookIcon,
  Twitter as TwitterIcon,
  Instagram as InstagramIcon,
} from "@mui/icons-material";

const FavoriteBorder = React.forwardRef<SVGSVGElement, React.SVGProps<SVGSVGElement>>((props, ref) => {
  return (
    <svg ref={ref} {...props} viewBox="0 0 24 24">
      <path d="M16.5 3c-1.74 0-3.41.81-4.5 2.09C10.91 3.81 9.24 3 7.5 3 4.42 3 2 5.42 2 8.5c0 3.78 3.4 6.86 8.55 11.54L12 21.35l1.45-1.32C18.6 15.36 22 12.28 22 8.5 22 5.42 19.58 3 16.5 3zm-4.4 15.55l-.1.1-.1-.1C7.14 14.24 4 11.39 4 8.5 4 6.5 5.5 5 7.5 5c1.54 0 3.04.99 3.57 2.36h1.87C13.46 5.99 14.96 5 16.5 5c2 0 3.5 1.5 3.5 3.5 0 2.89-3.14 5.74-7.9 10.05z" />
    </svg>
  );
});

export const Icons = {
  ArrowBack: ArrowBackIcon,
  ShoppingCart: ShoppingCartIcon,
  Search: SearchIcon,
  Person: PersonIcon,
  Close: CloseIcon,
  ExpandMore: ExpandMoreIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  KeyboardArrowLeft: KeyboardArrowLeftIcon,
  KeyboardArrowRight: KeyboardArrowRightIcon,
  LocalShipping: LocalShippingIcon,
  Verified: VerifiedUserIcon,
  VerifiedUser: VerifiedUserIcon,
  Support: SupportAgentIcon,
  SupportAgent: SupportAgentIcon,
  AddShoppingCart: AddShoppingCartIcon,
  CreditCard: CreditCardIcon,
  CheckCircle: CheckCircleIcon,
  LocationOn: LocationOnIcon,
  Email: EmailIcon,
  Lock: LockIcon,
  Visibility: VisibilityIcon,
  VisibilityOff: VisibilityOffIcon,
  Star: StarIcon,
  Cancel: DeleteIcon,
  MoreVert: MoreVertIcon,
  Refresh: RefreshIcon,
  Home: HomeIcon,
  TrendingUp: TrendingUpIcon,
  FilterList: FilterListIcon,
  Undo: UndoIcon,
  Send: SendIcon,
  ThumbUp: ThumbUpIcon,
  Nature: NatureIcon,
  Groups: GroupsIcon,
  Business: BusinessIcon,
  Phone: PhoneIcon,
  Map: MapIcon,
  CalendarToday: CalendarTodayIcon,
  Payment: PaymentIcon,
  AttachMoney: AttachMoneyIcon,
  Inventory: InventoryIcon,
  LocalOffer: LocalOfferIcon,
  Description: DescriptionIcon,
  People: PeopleIcon,
  Receipt: ReceiptIcon,
  Shield: ShieldIcon,
  CameraAlt: CameraAltIcon,
  YouTube: YouTubeIcon,
  Facebook: FacebookIcon,
  Twitter: TwitterIcon,
  Instagram: InstagramIcon,
  Favorite: FavoriteIcon,
  FavoriteBorder,
  FavoriteBorderIcon: FavoriteBorder,
};

export {
  ArrowBackIcon as ArrowBack,
  ShoppingCartIcon as ShoppingCart,
  SearchIcon as Search,
  PersonIcon as Person,
  CloseIcon as Close,
  ExpandMoreIcon as ExpandMore,
  ChevronLeftIcon as ChevronLeft,
  ChevronRightIcon as ChevronRight,
  KeyboardArrowLeftIcon as KeyboardArrowLeft,
  KeyboardArrowRightIcon as KeyboardArrowRight,
  LocalShippingIcon as LocalShipping,
  VerifiedUserIcon as Verified,
  VerifiedUserIcon as VerifiedUser,
  SupportAgentIcon as Support,
  SupportAgentIcon as SupportAgent,
  AddShoppingCartIcon as AddShoppingCart,
  CreditCardIcon as CreditCard,
  CheckCircleIcon as CheckCircle,
  LocationOnIcon as LocationOn,
  EmailIcon as Email,
  LockIcon as Lock,
  VisibilityIcon as Visibility,
  VisibilityOffIcon as VisibilityOff,
  StarIcon as Star,
  DeleteIcon as Cancel,
  MoreVertIcon as MoreVert,
  RefreshIcon as Refresh,
  HomeIcon as Home,
  TrendingUpIcon as TrendingUp,
  FilterListIcon as FilterList,
  UndoIcon as Undo,
  SendIcon as Send,
  ThumbUpIcon as ThumbUp,
  NatureIcon as Nature,
  GroupsIcon as Groups,
  BusinessIcon as Business,
  PhoneIcon as Phone,
  MapIcon as Map,
  CalendarTodayIcon as CalendarToday,
  PaymentIcon as Payment,
  AttachMoneyIcon as AttachMoney,
  InventoryIcon as Inventory,
  LocalOfferIcon as LocalOffer,
  DescriptionIcon as Description,
  PeopleIcon as People,
  ReceiptIcon as Receipt,
  ShieldIcon as Shield,
  CameraAltIcon as CameraAlt,
  YouTubeIcon as YouTube,
  FacebookIcon as Facebook,
  TwitterIcon as Twitter,
  InstagramIcon as Instagram,
  FavoriteIcon as Favorite,
  FavoriteBorder,
  FavoriteBorder as FavoriteBorderIcon,
};

export default Icons;